name: Generate GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate profile summary cards
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: PrathamRajendraPednekar
          THEME: nord_dark
